controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
controller.right.onEvent(ControllerButtonEvent.Repeated, function () {
    mySprite.x += 2
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
	
})
controller.left.onEvent(ControllerButtonEvent.Repeated, function () {
    mySprite.x += -2
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    777777ffff..............
    .777777777f.............
    .7777777777f............
    .7777777777f............
    .77777777777f...........
    .77777ffff77f...........
    fffffffeeefff...........
    ffe44ebf44eef...........
    fee4e41f44ef............
    .feee44444f.............
    ..f7777777f.............
    ..f77744ccc.............
    ...77777cdc.............
    ...f7777cddc............
    ....fffffcddc...........
    .....fff..cddc..........
    ...........cdc..........
    ............cc..........
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
forever(function () {
    music.play(music.stringPlayable("C B - G E - E C5 ", 120), music.PlaybackMode.UntilDone)
})
